In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Creating a sample dataset with missing values and categorical features
data = {'age': [25, 30, np.nan, 40, 45],
        'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'city': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
        'income': [50000, 60000, 70000, np.nan, 90000]}

df = pd.DataFrame(data)

In [3]:
df.head()

    age  gender      city   income
0  25.0    Male  New York  50000.0
1  30.0  Female    London  60000.0
2   NaN    Male     Paris  70000.0
3  40.0  Female     Tokyo      NaN
4  45.0    Male    Sydney  90000.0

In [4]:
print(df.isnull().sum())

age       1
gender    0
city      0
income    1
dtype: int64

In [5]:
df.describe()

             age        income
count   4.000000      4.000000
mean   35.000000  67500.000000
std     9.128709  17078.251277
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    35.000000  65000.000000
75%    41.250000  75000.000000
max    45.000000  90000.000000

In [6]:
print("Missing values in the dataset:\n", df.isnull().sum())

Missing values in the dataset:
 age       1
gender    0
city      0
income    1
dtype: int64

In [7]:
df['age']

0    25.0
1    30.0
2     NaN
3    40.0
4    45.0
Name: age, dtype: float64

In [8]:
# 2. Replace missing values in 'age' column with the mean age.
df['age'].fillna(df['age'].mean(), inplace=True)

In [9]:
df.head()

    age  gender      city   income
0  25.0    Male  New York  50000.0
1  30.0  Female    London  60000.0
2  35.0    Male     Paris  70000.0
3  40.0  Female     Tokyo      NaN
4  45.0    Male    Sydney  90000.0

In [10]:
# 3. Replace missing values in 'income' column with the median income.
df['income'].fillna(df['income'].median(), inplace=True)